//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILO
{
    using DesktopApplication.Core.Constants;
    using System;
    using System.Collections.Generic;

    public partial class CPN_Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CPN_Company()
        {
            this.LPS_LotteryPointSale = new HashSet<LPS_LotteryPointSale>();
        }
    
        public long CPN_Id { get; set; }
        public string CPN_Code { get; set; }
        public string CPN_DisplayName { get; set; }
        public string CPN_Description { get; set; }
        public System.DateTime CPN_CreateDate { get; set; }

        public long copy(CPN_Company pCompany)
        {
            long actualStatus = SystemConstants.SYNC_STATUS_COMPLETED;
            this.CPN_Code = pCompany.CPN_Code;
            this.CPN_DisplayName = pCompany.CPN_DisplayName;
            this.CPN_Description = pCompany.CPN_Description;
            this.CPN_CreateDate = pCompany.CPN_CreateDate;
            return actualStatus;
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LPS_LotteryPointSale> LPS_LotteryPointSale { get; set; }
    }
}
