//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBL_DrawBalance
    {
        public long DBL_Id { get; set; }
        public long LTD_LotteryDraw { get; set; }
        public long DBL_SaleImport { get; set; }
        public long DBL_PayImport { get; set; }
    
        public virtual LTD_LotteryDraw LTD_LotteryDraw1 { get; set; }
    }
}
