//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNW_DrawNumberWinning
    {
        public long LTD_LotteryDraw { get; set; }
        public string DNW_FirtsNumber { get; set; }
        public string DNW_SecondNumber { get; set; }
        public string DNW_ThirdNumber { get; set; }
        public System.DateTime DNW_CreateDate { get; set; }
        public long SYS_SynchronyStatus { get; set; }
    
        public virtual SYS_SynchronyStatus SYS_SynchronyStatus1 { get; set; }
        public virtual LTD_LotteryDraw LTD_LotteryDraw1 { get; set; }
    }
}
