//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERV_ErrorEvents
    {
        public long ERV_Id { get; set; }
        public System.DateTime ERV_EventDate { get; set; }
        public string ERV_Error { get; set; }
        public string ERV_Track { get; set; }
        public string ERV_Origin { get; set; }
        public string ERV_User { get; set; }
    }
}
