//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LDS_LotteryDrawStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LDS_LotteryDrawStatus()
        {
            this.LTD_LotteryDraw = new HashSet<LTD_LotteryDraw>();
        }
    
        public long LDS_Id { get; set; }
        public string LDS_Code { get; set; }
        public string LDS_DisplayName { get; set; }
        public string LDS_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LTD_LotteryDraw> LTD_LotteryDraw { get; set; }
    }
}
