//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILO
{
    using DesktopApplication.Core.Constants;
    using System;
    using System.Collections.Generic;

    public partial class LGV_LoginEvents
    {
        public long LGV_Id { get; set; }
        public System.DateTime LGV_EventDate { get; set; }
        public string LGV_IpAdress { get; set; }
        public string LGV_User { get; set; }
        public string LGV_DeviceId { get; set; }

        public long copy(LGV_LoginEvents pLoginEvent)
        {
            long actualStatus = SystemConstants.SYNC_STATUS_COMPLETED;
            this.LGV_EventDate = pLoginEvent.LGV_EventDate;
            this.LGV_IpAdress = pLoginEvent.LGV_IpAdress;
            this.LGV_User = pLoginEvent.LGV_User;
            this.LGV_DeviceId = pLoginEvent.LGV_DeviceId;
            return actualStatus;
        }
    }
}
