//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LLN_LotteryListNumber
    {
        public long LLN_Id { get; set; }
        public long LTL_LotteryList { get; set; }
        public long LNR_LotteryNumber { get; set; }
        public long LLN_Import { get; set; }
    }
}
