//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LLS_LotteryListStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LLS_LotteryListStatus()
        {
            this.LTL_LotteryList = new HashSet<LTL_LotteryList>();
        }
    
        public long LLS_Id { get; set; }
        public string LLS_Code { get; set; }
        public string LLS_DisplayName { get; set; }
        public string LLS_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LTL_LotteryList> LTL_LotteryList { get; set; }
    }
}
