//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LND_ListNumberDetail
    {
        public long LND_Id { get; set; }
        public long LTL_LotteryList { get; set; }
        public long LNR_LotteryNumber { get; set; }
        public long LND_Import { get; set; }
    
        public virtual LTL_LotteryList LTL_LotteryList1 { get; set; }
        public virtual LNR_LotteryNumber LNR_LotteryNumber1 { get; set; }
    }
}
