//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LPF_LotteryPrizeFactor
    {
        public long LPF_Id { get; set; }
        public long LPS_LotteryPointSale { get; set; }
        public long LDT_LotteryDrawType { get; set; }
        public double LPF_FirtsPrizeFactor { get; set; }
        public double LPF_SecondPrizeFactor { get; set; }
        public double LPF_ThirdPrizeFactor { get; set; }
        public long SYS_SynchronyStatus { get; set; }
    
        public virtual LDT_LotteryDrawType LDT_LotteryDrawType1 { get; set; }
        public virtual SYS_SynchronyStatus SYS_SynchronyStatus1 { get; set; }
        public virtual LPS_LotteryPointSale LPS_LotteryPointSale1 { get; set; }
    }
}
