//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTD_LotteryDraw
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LTD_LotteryDraw()
        {
            this.LTL_LotteryList = new HashSet<LTL_LotteryList>();
        }
    
        public long LTD_Id { get; set; }
        public System.DateTime LTD_CreateDate { get; set; }
        public long LDT_LotteryDrawType { get; set; }
        public long LTD_Status { get; set; }
    
        public virtual LDT_LotteryDrawType LDT_LotteryDrawType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LTL_LotteryList> LTL_LotteryList { get; set; }
    }
}
