//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTL_LotteryList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LTL_LotteryList()
        {
            this.LND_ListNumberDetail = new HashSet<LND_ListNumberDetail>();
        }
    
        public long LTL_Id { get; set; }
        public long LPS_LotteryPointSale { get; set; }
        public long LTD_LotteryDraw { get; set; }
        public string LTL_CustomerName { get; set; }
        public System.DateTime LTL_CreateDate { get; set; }
        public long LLS_LotteryListStatus { get; set; }
        public long SYS_SynchronyStatus { get; set; }
    
        public virtual LLS_LotteryListStatus LLS_LotteryListStatus1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LND_ListNumberDetail> LND_ListNumberDetail { get; set; }
        public virtual LPS_LotteryPointSale LPS_LotteryPointSale1 { get; set; }
        public virtual LTD_LotteryDraw LTD_LotteryDraw1 { get; set; }
        public virtual SYS_SynchronyStatus SYS_SynchronyStatus1 { get; set; }
    }
}
