//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTL_LotteryList
    {
        public long LTD_Id { get; set; }
        public long LTD_LotteryDraw { get; set; }
        public long LPS_LotteryPointSale { get; set; }
        public long LTD_Status { get; set; }
    
        public virtual LPS_LotteryPointSale LPS_LotteryPointSale1 { get; set; }
        public virtual LTD_LotteryDraw LTD_LotteryDraw1 { get; set; }
    }
}
