//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSP_PointSaleParameter
    {
        public string PSP_Name { get; set; }
        public string PSP_Value { get; set; }
        /*
        public PSP_PointSaleParameter(string pSP_Name, string pSP_Value)
        {
            PSP_Name = pSP_Name;
            PSP_Value = pSP_Value;
        }
        */

    }
}
