//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_SynchronyStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_SynchronyStatus()
        {
            this.DNW_DrawNumberWinning = new HashSet<DNW_DrawNumberWinning>();
            this.LPF_LotteryPrizeFactor = new HashSet<LPF_LotteryPrizeFactor>();
            this.LPS_LotteryPointSale = new HashSet<LPS_LotteryPointSale>();
            this.LTL_LotteryList = new HashSet<LTL_LotteryList>();
            this.AUS_ApplicationUser = new HashSet<AUS_ApplicationUser>();
            this.LNR_LotteryNumber = new HashSet<LNR_LotteryNumber>();
        }
    
        public long SYS_Id { get; set; }
        public string SYS_Code { get; set; }
        public string SYS_DisplayName { get; set; }
        public string SYS_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DNW_DrawNumberWinning> DNW_DrawNumberWinning { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LPF_LotteryPrizeFactor> LPF_LotteryPrizeFactor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LPS_LotteryPointSale> LPS_LotteryPointSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LTL_LotteryList> LTL_LotteryList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUS_ApplicationUser> AUS_ApplicationUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LNR_LotteryNumber> LNR_LotteryNumber { get; set; }
    }
}
