//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_SynchronyStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_SynchronyStatus()
        {
            this.DNW_DrawNumberWinning = new HashSet<DNW_DrawNumberWinning>();
        }
    
        public long SYS_Id { get; set; }
        public string SYS_Code { get; set; }
        public string SYS_Description { get; set; }
        public string SYS_DisplayName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DNW_DrawNumberWinning> DNW_DrawNumberWinning { get; set; }
    }
}
