//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILO
{
    using DesktopApplication.Core.Constants;
    using System;
    using System.Collections.Generic;

    public partial class USR_UserRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USR_UserRole()
        {
            this.AUS_ApplicationUser = new HashSet<AUS_ApplicationUser>();
        }
    
        public long USR_Id { get; set; }
        public string USR_DisplayName { get; set; }
        public string USR_Description { get; set; }
        public System.DateTime USR_CreateDate { get; set; }

        public long copy(USR_UserRole pUserRole)
        {
            long actualStatus = SystemConstants.SYNC_STATUS_COMPLETED;
            this.USR_DisplayName = pUserRole.USR_DisplayName;
            this.USR_Description = pUserRole.USR_Description;
            this.USR_CreateDate = pUserRole.USR_CreateDate;
            return actualStatus;
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUS_ApplicationUser> AUS_ApplicationUser { get; set; }
    }
}
