//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILO
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR_UserRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USR_UserRole()
        {
            this.AUS_ApplicationUser = new HashSet<AUS_ApplicationUser>();
        }
    
        public long USR_Id { get; set; }
        public string CPN_DisplayName { get; set; }
        public string CPN_Description { get; set; }
        public System.DateTime CPN_CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUS_ApplicationUser> AUS_ApplicationUser { get; set; }
    }
}
